### ISSUE TITLE
Resizing not working properly

### ISSUE THREAD

**Issue by Halamix2** [MovingBlocks/Terasology#2591]
### What you were trying to do
Resize window

### What actually happened
window resized but not the "rendering area" (something like #2490 but for blocks)
Skybox and water are rendered as expected
outline is visible on line between rendered zone and empty one (when outline is enabled in options)

### How to reproduce

* Step 1 turn on outilne in graphic settings
* Step 2 resize window before joining server or opening local game (after loading world it won't work)
* Step 3 see weird things going on

###More sophisticated explanation

After starting Terasology, entering game and resizing this bug occurs. After quitting game without quitting Terasology, entering game again and resizing bug #2490 occurs but not this one, and bug 2490 stays on the screen even after quitting game and resizing window again (skybox rendering width stays the same all the time when bug #2490 occurs)

### Log details and game version  

version 1 836 alpha 2016-11-05T03:55:30Z
[Terasology-.log.txt](https://github.com/MovingBlocks/Terasology/files/573349/Terasology-.log.txt)
[Terasology-init.log.txt](https://github.com/MovingBlocks/Terasology/files/573350/Terasology-init.log.txt)
[Terasology-menu.log.txt](https://github.com/MovingBlocks/Terasology/files/573348/Terasology-menu.log.txt)
[Terasology-mmo.to-188.68.52.110-25778.log.txt](https://github.com/MovingBlocks/Terasology/files/573351/Terasology-mmo.to-188.68.52.110-25778.log.txt)

### screens  
http://i.imgur.com/2KSFJex.png
http://i.imgur.com/NhzE3DE.png

### Computer details

OS: Ubuntu 16.10 yakkety
Kernel: x86_64 Linux 4.8.0-26-generic
Resolution: 1366x768
CPU: Intel Core i5-5200U CPU @ 2.7GHz
GPU: GeForce 920M (Nvidia drivers 370.28)
RAM: 7886MiB
Java version: 1.8.0_111

**Comment by emanuele3d** [comment]
Thank you @Halamix2 for reporting this. I managed to reproduce it. I'll see what I can do about it.

**Comment by emanuele3d** [comment]
While I did manage to reproduce it, it took me a while to reproduce it reliably. For posterity, the steps I found most reliable are:

- Start Terasology in Windowed Mode with Outline OFF
- Go to the Video Settings and turn it ON
- Go to the Main Menu
- Resize the window to nearly full screen 
- Load  up a game (everything will be normal)
- Bring up the In-game menu
- Resize the window back down
- Exit the game (but not Terasology)
- Go to the Video Settings and turn Outline OFF
- Go to the Main Menu
- Resize the window to nearly full screen
- Load up a game: the sky is cropped

**Comment by emanuele3d** [comment]
This _should_ be fixed in #2593. Can you verify @Halamix2? Or do you need to wait for the change to be merged before you can test it?

**Comment by Cervator** [comment]
Hey @Halamix2 could you confirm with the latest build or the `develop` branch and reopen this if not fixed?

Keep in mind #2528 and #2490 are separate issues and still valid, just concerned about the outline shader here (and any incremental improvements to resizing in general)

**Comment by emanuele3d** [comment]
Shut. I think #2593 actually fixed #2490 rather than this one. Sorry for the mix up.

I did notice some problem with the outline shader (aka Sobel) but I have not investigated it.

**Comment by Tropid** [comment]
While I'm trying to go through the code base I took a look at this issue. I can reliably reproduce the problem, but in my case, a black border appears. So if my window has a size of 1276 pixels and I rescale it the viewport for the whole world stays at 1276. The HUD though scales up.

After some debugging, I noticed that there is at least one `SetViewportToSizeOfTask` which still has the old window width saved. This leads to a `glViewport` call with the wrong width and to this problem.

I changed the `glViewport` call to always use the width of the window and this issue disappeared. I guess if we can find the reason why the width of this `SetViewportToSizeOfTask` is not updated on resize we can fix this.

**Comment by TimVerhaegen** [comment]
This is what happens whenever you resize it in the launcher (which I always do) and then join the game and wait for a moment. Not sure how to replicate this 100%, but just resize it in the launcher and let it sit there for an hour. The difference between this one and the regular one, is the color. Goodluck! 

![cc3cbb264a5c4025b100ea3de9aded6c](https://cloud.githubusercontent.com/assets/17968114/21746228/221a1224-d53e-11e6-8484-31c507752f00.png)

**Comment by Cervator** [comment]
FYI: "Launcher" == "Main Menu" don't forget :D

Not related to the TerasologyLauncher :-)

Other note relates to this including color unlike another symptom from resizing that results in black/grey/white everything

**Comment by Cervator** [comment]
Closing as fixed by #2844!
