### ISSUE TITLE
Animated menus can cause issues returning from some screens

### ISSUE THREAD

**Issue by Halamix2** [MovingBlocks/Terasology#2762]
### What you were trying to do
Close credits and see menu
### What actually happened
I see only background
### How to reproduce
* Open Terasology dev 1916
* enable "animated menus" in options
* ~~click "credits"->"back"~~ (fixed)
  * or "singleplayer"->"back"->"singleplayer"
  * or "singleplayer"->"back->"multiplayer" (any other combination should work)
  * or "multiplayer"->"back"->"singleplayer"
  * in short:  "singleplayer"/"multiplayer"->"back"->anything except single or multi any number of times->single/multi
* See only background image instead of menu

### Log details and game version
 Terasology dev 1916  
### Computer details
 OS: Ubuntu 16.10 yakkety, kernel: x86_64 Linux 4.8.0-34-generic
 dual-screen
 CPU: Intel Core i5-5200U CPU @ 2.7GHz
 Java version "1.8.0_121"
 GPU: GeForce 920M
 RAM: 7886MiB

**Comment by smsunarto** [comment]
Have you tried running from source? Does this problem persist there too?

**Comment by Halamix2** [comment]
The problem is fixed when running form source (I should've checked that before, sorry)

**Comment by Cervator** [comment]
Even if it is fine when running from source that could still indicate an issue if it happens consistently when run from binary - we get such bugs on occasion :-)

I just checked with Omega 661 (about a week old) and I could look at the credits then go back without trouble. Could you re-check via binary, see if it happens again? Was the game launched regularly or via the Launcher?

**Comment by Halamix2** [comment]
Problem exists when running dev 1916 from the Launcher, running from "run_linux.sh" works fine

**Comment by iojw** [comment]
I'm unable to recreate this on my Windows 10 machine running dev 1916 from the Launcher. Potentially a Linux issue?

**Comment by smsunarto** [comment]
It seems to be coming from "Animated Menus" option being enabled. Reproduced successfully on Ubuntu 16.04 LTS

**Comment by Halamix2** [comment]
It seems that "animated menus" option is causing it,
Ways to reproduce with "animated menus" turned on:
* "credits"->"back"
* "singleplayer"->"back"->"singleplayer"

**Comment by smsunarto** [comment]
@Halamix2 Please update the *How to reproduce* part of your issue :)

**Comment by Malanius** [comment]
Can confirm this running from source on Ubuntu 16.04 too, but happens not only for the credits but for any animated menu transition for me.
For credits immediately, for Single player and Create game menus always the 3rd animated transition.
Remaining menus (Settings, Join Game) seems unaffected by this. Disabling "Animated Menus" helps.

This started happening after last package updates, which included new nVidia drivers (using nVidia PPAs), so it might be related.
I'll try on W10 also and update afterwards.

**Comment by Halamix2** [comment]
The "credits" part should be fixed in #2772, singleplayer/multiplayer part of this bug may be trickier to fix since it occurs only after 3rd transition (and isLowerLayerVisible() is already there)

**Comment by Halamix2** [comment]
Main menu creates SelectGameScreen object, which is responsible for single/multi.  
If I'm correct clicking on back button without animated menus deletes this object and MainMenuScreen creates new one.  
But with animated menus after clicking back, SelectGameScreen object is not destroyed until it leaves the screen, but in the meantime MainMenuScreen creates another instance of SelectGameScreen. Is it possible that wrong instance of MainMenuScreen is deleted ("new" one instead of "old" one, like in heap)?

**Comment by Cervator** [comment]
Re-opening - only partially fixed (with #2772 merged the credits screen is OK now, single -> back -> single is still not)

**Comment by Malanius** [comment]
@Halamix2 I don't think the new instance gets deleted. When pressing Escape key on such undisplayed screen, it is shown for a brief time before it is moved away by animation.
I don't know how the menu works yet, but if someone could point me to the animated menus system, I'll try to look at it.

**Comment by Cervator** [comment]
Heya @Malanius - any more eyes on the bug would be appreciated! :-)

In IntelliJ it tends to be easy to find stuff. In this case I did `CTRL-N` (class file search) then entered "animat" and spotted a few classes in the `org.terasology.rendering.nui.animation` package. That looks to be a good place to start.

**Comment by Malanius** [comment]
So finally, nVidia released new driver so I could test it on W10 also. 
I can confirm that this issue is present on W10 too.

**Comment by 0shine0** [comment]
One more thing to note is that when we click "singlePlayer" or "multiPlayer" for very first time, the buttons of next screen appear without sliding animation. After that when we go back and then click again the actual bug starts that is mentioned in this issue.
